In [2]:
import numpy as np
import matplotlib as plt

In [3]:
array1= np.array([[1,2,3], [4,5,6]])
array2= np.random.rand(3,3)
array3= np.zeros((4,4))



np.save('array1.npy', array1)
np.save('array2.npy', array2)
np.save('array3.npy', array3)  # file save ho gay , but show nhi ho rha h

In [4]:
loaded_array1 = np.load('array1.npy')
loaded_array2 = np.load('array2.npy')
loaded_array3 = np.load('array3.npy')
print("\n\n Array1: \n", loaded_array1)
print("\n\nArray2: \n",loaded_array2)
print("\n\nArray3: \n", loaded_array3)



 Array1: 
 [[1 2 3]
 [4 5 6]]


Array2: 
 [[0.62252536 0.86214672 0.32081387]
 [0.74191528 0.21983949 0.78949656]
 [0.62510826 0.05754813 0.28926168]]


Array3: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
try:
    logo = np.load('numpy-logo.npy')

    # display
    plt.figure(figsize=(10, 5))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title("Numpy logo ")
    plt.grid(False)

    dark_logo=1-logo
    plt.subplot(122)
    plt.imshow(dark_logo)
    plt.title("numpy dark logo")
    plt.grid(False)

except FileNotFoundError:
    print("numpy logo file not found ")

numpy logo file not found 
