In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
array1= np.array([[1,2,3], [4,5,6]])
array2= np.random.rand(3,3)
array3= np.zeros((4,4))



np.save('array1.npy', array1)
np.save('array2.npy', array2)
np.save('array3.npy', array3)  # file save ho gay , but show nhi ho rha h

In [3]:
loaded_array1 = np.load('array1.npy')
loaded_array2 = np.load('array2.npy')
loaded_array3 = np.load('array3.npy')
print("\n\n Array1: \n", loaded_array1)
print("\n\nArray2: \n",loaded_array2)
print("\n\nArray3: \n", loaded_array3)



 Array1: 
 [[1 2 3]
 [4 5 6]]


Array2: 
 [[0.54798927 0.30211495 0.27178615]
 [0.85348041 0.73603799 0.96928431]
 [0.71991218 0.80506743 0.67826715]]


Array3: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
try:
    logo = np.load('numpy-logo.npy')

    # display
    plt.figure(figsize=(10, 5))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title("Numpy logo ")
    plt.grid(False)

    dark_logo=1-logo
    plt.subplot(122)
    plt.imshow(dark_logo)
    plt.title("numpy dark logo")
    plt.grid(False)

except FileNotFoundError:
    print("numpy logo file not found ")