In [18]:
import numpy as np

arr_1d=[1,2,3]
print("1D array: ", arr_1d)

arr_2d=[[2,3,4],[4,5,6]]
print("2D array: ", arr_2d)

1D array:  [1, 2, 3]
2D array:  [[2, 3, 4], [4, 5, 6]]


In [19]:
# list multiplication
py_list=[1,2,3]
print("Python list multiplication: ", py_list*2)


# array multiplication
py_array=np.array([1,2,3])
print("python matrix multiplication: ", py_array*2)

Python list multiplication:  [1, 2, 3, 1, 2, 3]
python matrix multiplication:  [2 4 6]


In [20]:
# add two matrix

matrix_1=np.array([[1,2],[3,5]])
matrix_2=np.array([[2,5],[7,9]])

add_matrix= matrix_1 + matrix_2
print("Addition of a matrix: \n", add_matrix)

Addition of a matrix: 
 [[ 3  7]
 [10 14]]


In [21]:
# mul two matrix


mul_matrix= matrix_1 * matrix_2
print("multipliction of a matrix: \n", mul_matrix)

multipliction of a matrix: 
 [[ 2 10]
 [21 45]]


In [22]:
import time

start=time.time()
py_list=[1*2 for i in range(100000000)]
print("\n list operation time: ", time.time()-start)


start = time.time()
np_array= np.arange(100000000)*2
print("numpy operation time: ", time.time()-start)


 list operation time:  5.15657114982605
numpy operation time:  0.572533130645752


### create array for scratch


In [23]:
# Creating a 3x4 zero array
zero=np.zeros([3,4])
print("Zero array: \n", zero)

# Creating a 3x4 ones array
one=np.ones([3,4])
print("ones array: \n", one)

# Creating an identity matrix --> 5x5
Identity=np.identity(5)
print("Identity array: \n", Identity)

Zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity array: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:

full=np.full((3,3),7)
print("full array: \n", full)


print("Random value:", np.random.randint(1, 10))

full array: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random value: 9


### Vector, Matrix, Tensor


In [25]:
vector=np.array([1,2,3])
print("vector", vector)

matrix=np.array([[1,2,3],
                 [4,5,6]])
print("matrix: \n", matrix)

tensor=np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print("Tensor: \n", tensor)

vector [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [26]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

shape  (2, 3)
Dimension  2
Size  6
DType  int64


### - Array Reshaping

In [29]:


arr=np.arange(12)
print("original array ",arr)

reshape=arr.reshape((3,4))
print("\n Reshaped array ", reshape)

flattened=reshape.flatten()
print("\n flattened arr ", flattened)

# ravel (returns view, instead of copy)
reveled= reshape.ravel()
print("\n reveled array ", reveled)

# transpose 

transpose = reshape.T
print("\n Transposed array :\n", transpose)

original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened arr  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
