## Numpy Array operations

In [2]:
import numpy as np

In [30]:
arr = np.array(range(1,11))
print("Arrat list: ", arr)
print("Basic slicing: ", arr[2:7])
print("with step: ", [1,8,3])
print("negative indexing: ", arr[-1])

Arrat list:  [ 1  2  3  4  5  6  7  8  9 10]
Basic slicing:  [3 4 5 6 7]
with step:  [1, 8, 3]
negative indexing:  10


In [31]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print("row 2, col 3 --> ",arr_2d[1,2])
print("row 3, col 1 --> ",arr_2d[2,1])
print("row 2, col 1 --> ",arr_2d[1,0])
print("row 1, col 1 --> ",arr_2d[0,0])


print("Entire row 2 --> ", arr_2d[1])
print("Entire col 3 --> ", arr_2d[:,2])

row 2, col 3 -->  6
row 3, col 1 -->  8
row 2, col 1 -->  4
row 1, col 1 -->  1
Entire row 2 -->  [4 5 6]
Entire col 3 -->  [3 6 9]


### Sorting

In [32]:
arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,5]])

print("sorted 2D array by column : \n", np.sort(arr_2d_unsorted, axis=0))
print("sorted 2D array by row : \n", np.sort(arr_2d_unsorted, axis=1))

sorted 2D array by column : 
 [[1 1]
 [2 2]
 [3 5]]
sorted 2D array by row : 
 [[1 3]
 [1 2]
 [2 5]]


## Filter

In [ ]:
numbers= np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers%2==0]
print("Even numbers: ", even_number)

Even numbers:  [ 2  4  6  8 10]


In [ ]:
# filter with mask

mask = numbers>5
print("number greater than 5: ",  numbers[mask])

number greater than 5:  [ 6  7  8  9 10]


In [38]:

indices=[0,2,4]
print("number index: ", numbers[indices])

where_result=np.where(numbers>5)
print("where result: ", where_result)
print("NP where: ", numbers[where_result])


number index:  [1 3 5]
where result:  (array([5, 6, 7, 8, 9]),)
NP where:  [ 6  7  8  9 10]


In [51]:
condition_array=np.where(numbers>5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing array

In [53]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1, arr2))
print( combined)


[1 2 3 4 5 6]


### Array compatibilty

In [55]:
a= np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9,3])

print("compatibility shapes: ", a.shape == b.shape)
print("compatibility shapes: ", a.shape == c.shape)



compatibility shapes:  True
compatibility shapes:  False


In [63]:
original=np.array([[1,2],
                   [3,4]])
new_row=np.array([5,6])

with_new_row=np.vstack((original, new_row))
print("original array :\n ", original)
print("with new row : \n", with_new_row)



original array :
  [[1 2]
 [3 4]]
with new row : 
 [[1 2]
 [3 4]
 [5 6]]


In [67]:

new_col = np.array([[7],[8]])
with_new_col= np.hstack((original, new_col))

print(" original array:\n ", original)
print("with new colum: \n", with_new_col)


 original array:
  [[1 2]
 [3 4]]
with new colum: 
 [[1 2 7]
 [3 4 8]]


In [80]:
arr = np.array([1,2,3,4,5,6,7])
print("Array Before deletion: ", arr)

deleted = np.delete(arr, (3,4,5))
print("Array After deletion:  ", deleted)

Array Before deletion:  [1 2 3 4 5 6 7]
Array After deletion:   [1 2 3 7]
