In [335]:
# numpy --> numerical python

import numpy as np

1D array

In [336]:
array_file_1D = np.array([1,8,4,6,5,2,3,7])
print(array_file_1D)

[1 8 4 6 5 2 3 7]


In [337]:
array_file_1D.shape

(8,)

2D array

In [338]:
array_file_2D = np.array([[2,3,4,5,6,7],
                          [3,4,5,6,7,8],
                          [5,6,7,8,9,10]])

print(array_file_2D)

[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 5  6  7  8  9 10]]


In [339]:
array_file_2D.shape

(3, 6)

3D array

In [340]:
array_file_3D = np.array([[[1,2,3,4],
                           [2,3,4,5,]],

                           [[3,4,5,6],
                           [5,6,7,8]],

                            [[9,10,11,12],
                             [12,13,14,15]]])

print(array_file_3D)

[[[ 1  2  3  4]
  [ 2  3  4  5]]

 [[ 3  4  5  6]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 14 15]]]


indexing and slicing


In [341]:
print(array_file_3D.itemsize, "bytes")

8 bytes


In [342]:
print(array_file_3D[1,1])

[5 6 7 8]


In [343]:
print(array_file_2D[2,2])

7


In [344]:
print(array_file_3D[2,0,3])

12


In [345]:
print(array_file_1D[1:])

[8 4 6 5 2 3 7]


In [346]:
print(array_file_2D[1:,1:])

[[ 4  5  6  7  8]
 [ 6  7  8  9 10]]


In [347]:
print(array_file_2D[2:,1:])

[[ 6  7  8  9 10]]


In [348]:
print(array_file_3D[0:2,1,1:])

[[3 4 5]
 [6 7 8]]


[14,15] in 3D

In [349]:
print(array_file_3D[2,1,2:])

[14 15]


In [350]:
15 in array_file_3D

True

arthmatic operation

In [351]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

print(a)

print(b)


[[1 2]
 [3 4]]
[[10 20]
 [30 40]]


In [352]:
a == b

array([[False, False],
       [False, False]])

In [353]:
# add

print(a+b)

[[11 22]
 [33 44]]


In [354]:
# subtract

print(a-b)
#
print(b-a)

[[ -9 -18]
 [-27 -36]]
[[ 9 18]
 [27 36]]


In [355]:
# multiplication

print(a*b)
print(b*a)

a*b == b*a

[[ 10  40]
 [ 90 160]]
[[ 10  40]
 [ 90 160]]


array([[ True,  True],
       [ True,  True]])

In [356]:
# division

print(a/b)
print(b/a)

[[0.1 0.1]
 [0.1 0.1]]
[[10. 10.]
 [10. 10.]]


In [357]:
# Floor division
print(b//a)

[[10 10]
 [10 10]]


In [358]:
# power

print(a**2)
print(a**3)
print(a**4)

[[ 1  4]
 [ 9 16]]
[[ 1  8]
 [27 64]]
[[  1  16]
 [ 81 256]]


Transpose

In [359]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [360]:
print(arr.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Sorting

In [361]:
arr_1D = np.array([2, 4, 6, 8, 10,1, 3, 5])
sort_1D = np.sort(arr_1D)
sort_1D

array([ 1,  2,  3,  4,  5,  6,  8, 10])

In [362]:
print(arr_1D)
print(np.sort(arr_1D))
print(np.sort(arr_1D)[::-1])

print( np.array(sorted(arr_1D, reverse=True)))


[ 2  4  6  8 10  1  3  5]
[ 1  2  3  4  5  6  8 10]
[10  8  6  5  4  3  2  1]
[10  8  6  5  4  3  2  1]


In [363]:
print(np.sort(array_file_1D))

[1 2 3 4 5 6 7 8]


In [364]:
print(np.sort(array_file_2D))

[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 5  6  7  8  9 10]]


In [365]:
print(np.sort(array_file_3D))

[[[ 1  2  3  4]
  [ 2  3  4  5]]

 [[ 3  4  5  6]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 14 15]]]


In [366]:
print(array_file_3D.T)

[[[ 1  3  9]
  [ 2  5 12]]

 [[ 2  4 10]
  [ 3  6 13]]

 [[ 3  5 11]
  [ 4  7 14]]

 [[ 4  6 12]
  [ 5  8 15]]]


In [367]:
print(array_file_2D.T)

[[ 2  3  5]
 [ 3  4  6]
 [ 4  5  7]
 [ 5  6  8]
 [ 6  7  9]
 [ 7  8 10]]


In [368]:
print(np.sort(array_file_2D, axis=0))

[[ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 5  6  7  8  9 10]]


In [369]:
print(np.sort(array_file_2D.T, axis=1))

[[ 2  3  5]
 [ 3  4  6]
 [ 4  5  7]
 [ 5  6  8]
 [ 6  7  9]
 [ 7  8 10]]


Argsort

In [370]:
print(np.sort(array_file_3D)) # sort array
print(np.argsort(array_file_3D)) # show sort index

[[[ 1  2  3  4]
  [ 2  3  4  5]]

 [[ 3  4  5  6]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [12 13 14 15]]]
[[[0 1 2 3]
  [0 1 2 3]]

 [[0 1 2 3]
  [0 1 2 3]]

 [[0 1 2 3]
  [0 1 2 3]]]


top 3 pick

In [371]:

top = np.array([3,7,9,1,2])

print(np.sort(top)) # sorted array
print(top) # orignal array
print(np.argsort(top)) # sort for top ranks


[1 2 3 7 9]
[3 7 9 1 2]
[3 4 0 1 2]


In [372]:
arr1 =[[1, 4, 2],
       [3, 6, 5]]

print(np.sort(arr1))
print(np.sort(arr1, axis=0))
print(np.sort(arr1, axis=1))

[[1 2 4]
 [3 5 6]]
[[1 4 2]
 [3 6 5]]
[[1 2 4]
 [3 5 6]]


Reshape

In [373]:
print(arr_1D)

[ 2  4  6  8 10  1  3  5]


In [374]:
print(arr_1D.reshape(4,2))

[[ 2  4]
 [ 6  8]
 [10  1]
 [ 3  5]]


2D to 1D

In [378]:
print(array_file_2D.reshape(-1))


[ 2  3  4  5  6  7  3  4  5  6  7  8  5  6  7  8  9 10]


Two methods

concat -> pandas [deals with labeled-data]

concatenate -> numpy [array-focused]





Statistical Operations: Mean, Median and Mode, Standard Deviation, Min, Max, Sum

np.median => Median

np.std => Standard Deviation

np.min => Minimum Value

np.max => Maximum Value

np.sum => Sum

In [380]:
arr = np.array([[3,4,5,],
               [6,7,8]])

In [385]:

print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.std(arr))
print(np.median(arr))

3
8
33
1.707825127659933
5.5


Data Creation ways of NumPy Arrays

In [387]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [394]:
arr = np.zeros((2,3,4), dtype=int)
arr

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [395]:
arr = np.zeros((2,3,4), dtype=str)
arr

array([[['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', '']],

       [['', '', '', ''],
        ['', '', '', ''],
        ['', '', '', '']]], dtype='<U1')

In [396]:
arr = np.ones((2,3,4), dtype=int)
arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [397]:
arr = np.full((2,3,4), 421)
arr

array([[[421, 421, 421, 421],
        [421, 421, 421, 421],
        [421, 421, 421, 421]],

       [[421, 421, 421, 421],
        [421, 421, 421, 421],
        [421, 421, 421, 421]]])

In [403]:
arr = np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.arange(start, stop, step_size)

In [406]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [408]:
arr = np.arange(3,10)
arr

array([3, 4, 5, 6, 7, 8, 9])

In [410]:
arr = np.arange(3,10,2)
arr

array([3, 5, 7, 9])

Random

In [421]:
arr = np.random.random((2,3))
print(arr)

[[0.40014674 0.20113111 0.44917499]
 [0.30652835 0.47563647 0.82758348]]


In [453]:
arr = np.random.randint( 0,15,size=(2, 3))
print(arr)


[[11  9  7]
 [ 8 13  3]]
